---
# Jenkins installation tasks (Docker-based)

- name: Create Jenkins directory
  file:
    path: /opt/jenkins
    state: directory
    mode: '0755'

- name: Create Jenkins data directory
  file:
    path: /opt/jenkins/jenkins_home
    state: directory
    mode: '0755'
    owner: 1000
    group: 1000

- name: Template Jenkins docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: /opt/jenkins/docker-compose.yml
    mode: '0644'

- name: Start Jenkins via Docker Compose
  shell: docker compose up -d
  args:
    chdir: /opt/jenkins
