apiVersion: v2
name: places-backend
description: A Helm chart for the Places Backend application
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: postgresql
    version: ">=17.0.0"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: ">=24.0.0"
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: minio
    version: ">=16.0.0"
    repository: https://charts.bitnami.com/bitnami
    condition: minio.enabled
