apiVersion: batch/v1
kind: Job
metadata:
  name: migrations
  namespace: places-backend
spec:
  backoffLimit: 4
  ttlSecondsAfterFinished: 300
  template:
    metadata:
      name: migrations
    spec:
      restartPolicy: OnFailure
      containers:
      - name: alembic
        image: places_backend-app:latest
        imagePullPolicy: Never
        command: ["alembic", "upgrade", "head"]
        workingDir: /app
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets
