apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "places-backend.fullname" . }}-config
  labels:
    {{- include "places-backend.labels" . | nindent 4 }}
data:
  DB_NAME: {{ .Values.env.DB_NAME | quote }}
  DB_USER: {{ .Values.env.DB_USER | quote }}
  DB_HOST: {{ .Release.Name }}-postgresql
  DB_PORT: {{ .Values.env.DB_PORT | quote }}
  REDIS_HOST: {{ .Release.Name }}-redis-master
  REDIS_PORT: {{ .Values.env.REDIS_PORT | quote }}
  MINIO_ENDPOINT: "{{ .Release.Name }}-minio:9000"
  MINIO_BUCKET: {{ .Values.env.MINIO_BUCKET | quote }}
  ALGORITHM: {{ .Values.env.ALGORITHM | quote }}
  ACCESS_TOKEN_EXPIRE_MINUTES: {{ .Values.env.ACCESS_TOKEN_EXPIRE_MINUTES | quote }}
  MINIO_SECURE: {{ .Values.env.MINIO_SECURE | quote }}
