{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "places-backend.fullname" . }}-pdb
  labels:
    {{- include "places-backend.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "places-backend.selectorLabels" . | nindent 6 }}
{{- end }}
