---
- import_playbook: check_ready.yml

- name: Deploy Urban Places Backend App
  hosts: vps
  become: true
  roles:
    - app
    - role: monitoring
      when: enable_monitoring | default(false) | bool
