apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: places-backend
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/vurados/places_backend.git
    targetRevision: feat/argoCD
    path: charts/places-backend
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: global.security.allowInsecureImages
          value: "true"
        - name: postgresql.image.registry
          value: public.ecr.aws
        - name: postgresql.image.repository
          value: bitnami/postgresql
        - name: postgresql.image.tag
          value: 15.1.0-debian-11-r0
        - name: redis.image.registry
          value: public.ecr.aws
        - name: redis.image.repository
          value: bitnami/redis
        - name: redis.image.tag
          value: 7.0.12-debian-11-r0
        - name: minio.image.registry
          value: public.ecr.aws
        - name: minio.image.repository
          value: bitnami/minio
        - name: minio.image.tag
          value: 2023.6.14-debian-11-r0
  destination:
    server: https://kubernetes.default.svc
    namespace: places-backend
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
